name: CI/CD Pipeline

   on:
     push:
       branches:
         - main
     pull_request:

   jobs:
     hello_ci_cd:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Run echo command
           run: echo "Hello CI/CD!"
   
